"""0010_sync_models

Revision ID: 0010_sync_models
Revises: 0009_revise_database_ids
Create Date: 2026-03-20 15:40:04.174952
"""

# revision identifiers, used by Alembic.
revision = "0010_sync_models"
down_revision = "0009_revise_database_ids"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Intentionally no-op.
    #
    # The previous autogeneration attempted a broad PK/FK rewrite and failed due
    # to ordering conflicts (FKs created before referenced columns existed).
    # Keep this revision as a safe head marker.
    pass


def downgrade() -> None:
    # No-op downgrade for matching no-op upgrade.
    pass
"""0010_sync_models

Revision ID: 0010_sync_models
Revises: 0009_revise_database_ids
Create Date: 2026-03-20 15:40:04.174952
"""

# revision identifiers, used by Alembic.
revision = "0010_sync_models"
down_revision = "0009_revise_database_ids"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Intentionally no-op.
    #
    # The previously auto-generated migration attempted broad PK/FK rewrites
    # and failed on existing databases due to operation ordering and FK dependency
    # conflicts (e.g. creating FKs to columns not yet created).
    pass


def downgrade() -> None:
    # No-op downgrade for matching no-op upgrade.
    pass
"""0010_sync_models

Revision ID: 0010_sync_models
Revises: 0009_revise_database_ids
Create Date: 2026-03-20 15:40:04.174952
"""

# revision identifiers, used by Alembic.
revision = "0010_sync_models"
down_revision = "0009_revise_database_ids"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Intentionally no-op.
    #
    # The auto-generated migration attempted broad PK/FK rewrites and fails
    # on existing databases due to operation ordering and dependency conflicts.
    # Prior revisions already carry the schema alignment for this branch.
    pass


def downgrade() -> None:
    # No-op downgrade for the no-op upgrade.
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_role_id_roles'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('users', 'user_updated_at')
    op.drop_column('users', 'user_created_at')
    op.drop_column('users', 'user_id')
    op.add_column('score_values', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('score_values', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('score_values', 'score_value_updated_at')
    op.drop_column('score_values', 'score_value_created_at')
    op.add_column('roles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('roles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.drop_column('roles', 'role_updated_at')
    op.drop_column('roles', 'role_created_at')
    op.drop_column('roles', 'role_id')
    op.add_column('questionnaire_questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('questionnaire_questions', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('questionnaire_questions_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('questionnaire_questions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questionnaire_questions', type_='foreignkey')
    op.create_foreign_key(op.f('questionnaire_questions_job_listing_id_fkey'), 'questionnaire_questions', 'job_listings', ['job_listing_id'], ['id'])
    op.drop_index(op.f('ix_questionnaire_questions_question_id'), table_name='questionnaire_questions')
    op.create_index(op.f('ix_questionnaire_questions_question_type_id'), 'questionnaire_questions', ['question_type_id'], unique=False)
    op.create_index(op.f('ix_questionnaire_questions_id'), 'questionnaire_questions', ['id'], unique=False)
    op.alter_column('questionnaire_questions', 'question_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('questionnaire_questions', 'question_updated_at')
    op.drop_column('questionnaire_questions', 'question_created_at')
    op.drop_column('questionnaire_questions', 'question_id')
    op.add_column('question_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('question_types', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('question_types', 'question_type_updated_at')
    op.drop_column('question_types', 'question_type_created_at')
    op.add_column('profiles', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('profiles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_profiles_profile_id'), table_name='profiles')
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.drop_column('profiles', 'profile_updated_at')
    op.drop_column('profiles', 'profile_created_at')
    op.drop_column('profiles', 'profile_id')
    op.add_column('job_metadata', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_metadata', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('job_metadata', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_metadata_metadata_id'), table_name='job_metadata')
    op.create_index(op.f('ix_job_metadata_id'), 'job_metadata', ['id'], unique=False)
    op.drop_column('job_metadata', 'metadata_updated_at')
    op.drop_column('job_metadata', 'metadata_created_at')
    op.drop_column('job_metadata', 'metadata_id')
    op.add_column('job_listings', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('job_listings_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('job_listings', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_listings', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_listings', sa.Column('slug', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('job_listings', sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('job_listings', sa.Column('date_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_listings', type_='unique')
    op.drop_index(op.f('ix_job_listings_listing_id'), table_name='job_listings')
    op.create_index(op.f('ix_job_listings_slug'), 'job_listings', ['slug'], unique=True)
    op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)
    op.drop_column('job_listings', 'listing_updated_at')
    op.drop_column('job_listings', 'listing_created_at')
    op.drop_column('job_listings', 'listing_slug')
    op.drop_column('job_listings', 'listing_date_end')
    op.drop_column('job_listings', 'listing_date_created')
    op.drop_column('job_listings', 'listing_id')
    op.add_column('job_listing_questions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_listing_questions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('job_listing_questions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_listing_questions', type_='foreignkey')
    op.drop_constraint(None, 'job_listing_questions', type_='foreignkey')
    op.create_foreign_key(op.f('job_listing_questions_job_listing_id_fkey'), 'job_listing_questions', 'job_listings', ['job_listing_id'], ['id'])
    op.create_foreign_key(op.f('job_listing_questions_question_id_fkey'), 'job_listing_questions', 'questionnaire_questions', ['question_id'], ['id'])
    op.drop_index(op.f('ix_job_listing_questions_job_listing_question_id'), table_name='job_listing_questions')
    op.create_unique_constraint(op.f('uq_job_listing_questions_job_listing_id_sequence_number'), 'job_listing_questions', ['job_listing_id', 'sequence_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_job_listing_questions_id'), 'job_listing_questions', ['id'], unique=False)
    op.alter_column('job_listing_questions', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('job_listing_questions', 'job_listing_question_updated_at')
    op.drop_column('job_listing_questions', 'job_listing_question_created_at')
    op.drop_column('job_listing_questions', 'job_listing_question_id')
    op.add_column('field_options', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('field_options', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('field_options', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_field_options_field_option_id'), table_name='field_options')
    op.create_index(op.f('ix_field_options_id'), 'field_options', ['id'], unique=False)
    op.drop_column('field_options', 'field_option_updated_at')
    op.drop_column('field_options', 'field_option_created_at')
    op.drop_column('field_options', 'field_option_id')
    op.add_column('application_submissions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('application_submissions', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('application_submissions_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('application_submissions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_submissions', type_='foreignkey')
    op.drop_constraint(None, 'application_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_application_submissions_user_id_users'), 'application_submissions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('application_submissions_job_listing_id_fkey'), 'application_submissions', 'job_listings', ['job_listing_id'], ['id'])
    op.drop_index(op.f('ix_application_submissions_application_submission_id'), table_name='application_submissions')
    op.create_index(op.f('ix_application_submissions_id'), 'application_submissions', ['id'], unique=False)
    op.drop_column('application_submissions', 'application_submission_updated_at')
    op.drop_column('application_submissions', 'application_submission_created_at')
    op.drop_column('application_submissions', 'application_submission_id')
    op.add_column('application_submission_status_events', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('application_submission_status_events', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'application_submission_status_events', type_='foreignkey')
    op.drop_constraint(None, 'application_submission_status_events', type_='foreignkey')
    op.create_foreign_key(op.f('application_submission_status_ev_application_submission_id_fkey'), 'application_submission_status_events', 'application_submissions', ['application_submission_id'], ['id'])
    op.create_foreign_key(op.f('application_submission_status_events_created_by_user_id_fkey'), 'application_submission_status_events', 'users', ['created_by_user_id'], ['id'])
    op.drop_column('application_submission_status_events', 'application_submission_status_event_updated_at')
    op.drop_column('application_submission_status_events', 'application_submission_status_event_created_at')
    op.add_column('application_statuses', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('application_statuses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('application_statuses', 'application_status_updated_at')
    op.drop_column('application_statuses', 'application_status_created_at')
    op.add_column('application_review_scores', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('application_review_scores', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('application_review_scores', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_review_scores', type_='foreignkey')
    op.drop_constraint(None, 'application_review_scores', type_='foreignkey')
    op.create_foreign_key(op.f('application_review_scores_application_submission_id_fkey'), 'application_review_scores', 'application_submissions', ['application_submission_id'], ['id'])
    op.create_foreign_key(op.f('application_review_scores_reviewer_user_id_fkey'), 'application_review_scores', 'users', ['reviewer_user_id'], ['id'])
    op.drop_index(op.f('ix_application_review_scores_application_review_score_id'), table_name='application_review_scores')
    op.create_index(op.f('ix_application_review_scores_id'), 'application_review_scores', ['id'], unique=False)
    op.alter_column('application_review_scores', 'score_value_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('application_review_scores', 'application_review_score_updated_at')
    op.drop_column('application_review_scores', 'application_review_score_created_at')
    op.drop_column('application_review_scores', 'application_review_score_id')
    op.add_column('application_review_comments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('application_review_comments', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('application_review_comments', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_review_comments', type_='foreignkey')
    op.drop_constraint(None, 'application_review_comments', type_='foreignkey')
    op.create_foreign_key(op.f('application_review_comments_application_submission_id_fkey'), 'application_review_comments', 'application_submissions', ['application_submission_id'], ['id'])
    op.create_foreign_key(op.f('application_review_comments_reviewer_user_id_fkey'), 'application_review_comments', 'users', ['reviewer_user_id'], ['id'])
    op.drop_index(op.f('ix_application_review_comments_application_review_comment_id'), table_name='application_review_comments')
    op.create_index(op.f('ix_application_review_comments_id'), 'application_review_comments', ['id'], unique=False)
    op.drop_column('application_review_comments', 'application_review_comment_updated_at')
    op.drop_column('application_review_comments', 'application_review_comment_created_at')
    op.drop_column('application_review_comments', 'application_review_comment_id')
    op.add_column('application_question_responses', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('application_question_responses', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('application_question_responses', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'application_question_responses', type_='foreignkey')
    op.drop_constraint(None, 'application_question_responses', type_='foreignkey')
    op.create_foreign_key(op.f('application_question_responses_application_submission_id_fkey'), 'application_question_responses', 'application_submissions', ['application_submission_id'], ['id'])
    op.create_foreign_key(op.f('application_question_responses_question_id_fkey'), 'application_question_responses', 'questionnaire_questions', ['question_id'], ['id'])
    op.drop_index(op.f('ix_application_question_responses_application_question_response_id'), table_name='application_question_responses')
    op.create_index(op.f('ix_application_question_responses_id'), 'application_question_responses', ['id'], unique=False)
    op.drop_column('application_question_responses', 'application_question_response_updated_at')
    op.drop_column('application_question_responses', 'application_question_response_created_at')
    op.drop_column('application_question_responses', 'application_question_response_id')
    op.create_table('dropdown_options',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dropdown_options_pkey'))
    )
    op.create_index(op.f('ix_dropdown_options_id'), 'dropdown_options', ['id'], unique=False)
    op.create_index(op.f('ix_dropdown_options_category'), 'dropdown_options', ['category'], unique=False)
    # ### end Alembic commands ###
